name: List directories
on: 
  push:
    branches: [master]
jobs:
  pwd:
    name: Print working directory
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: run
      run: pwd
  ls:
    name: List directory content
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: run
      run: ls -al
    
